import os

# Make dirs
os.mkdir('assets')
os.makedirs('checkpoints/RL')
os.mkdir('checkpoints/multiclass_categorization')
os.mkdir('checkpoints/regression')
os.mkdir('checkpoints/binary_categorization')
os.makedirs('data/binary_categorization/blockers/train')
os.mkdir('data/binary_categorization/blockers/val')
os.makedirs('data/multiclass_categorization/fivecard/train')
os.mkdir('data/multiclass_categorization/fivecard/val')
os.makedirs('data/multiclass_categorization/ninecard/train')
os.mkdir('data/multiclass_categorization/ninecard/val')
os.makedirs('data/multiclass_categorization/handranks/train')
os.mkdir('data/multiclass_categorization/handranks/val')
os.makedirs('data/regression/tencard/train')
os.mkdir('data/regression/tencard/val')
os.makedirs('data/regression/thirteencard/train')
os.mkdir('data/regression/thirteencard/val')
os.makedirs('data/regression/partial/train')
os.mkdir('data/regression/partial/val')
# Build data
os.system('python build_dataset.py -d fivecard -O data/multiclass_categorization/fivecard')
os.system('python build_dataset.py -d ninecard -O data/multiclass_categorization/ninecard')
os.system('python build_dataset.py -d tencard -O data/regression/tencard')
os.system('python build_dataset.py -d thirteencard -O data/regression/thirteencard')
os.system('python build_dataset.py -d blockers -O data/binary_categorization/blockers')
os.system('python build_dataset.py -d handranks -O data/multiclass_categorization/handranks')
os.system('python build_dataset.py -d partial -O data/regression/partial')