import os

# Make dirs
os.makedirs('assets')
os.makedirs('checkpoints/RL')
os.makedirs('checkpoints/multiclass_categorization')
os.makedirs('checkpoints/regression')
os.makedirs('checkpoints/binary_categorization')
os.makedirs('data/binary_categorization/blockers/train')
os.makedirs('data/binary_categorization/blockers/test')
os.makedirs('data/multiclass_categorization/fivecard/train')
os.makedirs('data/multiclass_categorization/fivecard/test')
os.makedirs('data/multiclass_categorization/ninecard/train')
os.makedirs('data/multiclass_categorization/ninecard/test')
os.makedirs('data/regression/tencard/train')
os.makedirs('data/regression/tencard/test')
os.makedirs('data/regression/thirteencard/train')
os.makedirs('data/regression/thirteencard/test')
os.makedirs('data/regression/partial/train')
os.makedirs('data/regression/partial/test')
# Build data
os.system('python build_dataset.py -d fivecard -O data/multiclass_categorization/fivecard')
os.system('python build_dataset.py -d ninecard -O data/multiclass_categorization/ninecard')
os.system('python build_dataset.py -d tencard -O data/regression/tencard')
os.system('python build_dataset.py -d thirteencard -O data/regression/thirteencard')
# os.system('python build_dataset.py -d partial -O data/regression/partial')
# os.system('python build_dataset.py -d blockers -O data/binary_categorization')